version: '3.8'

services:
  support_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: "support_db"
      POSTGRES_PASSWORD: 1234567!
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  django:
    container_name: support_web
    build:
      context: ./
      dockerfile: Dockerfile
    command:  bash -c "python src/manage.py migrate --noinput &&
              python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - support_db
volumes:
  postgres_data: